cmake \
-DBUILD_JASPER:BOOL=OFF \
-DBUILD_JPEG:BOOL=OFF \
-DBUILD_OPENEXR:BOOL=OFF \
-DBUILD_PERF_TESTS:BOOL=OFF \
-DBUILD_PNG:BOOL=OFF \
-DBUILD_TESTS:BOOL=OFF \
-DBUILD_TIFF:BOOL=OFF \
-DBUILD_WEBP:BOOL=OFF \
-DBUILD_ZLIB:BOOL=OFF \
-DBUILD_opencv_apps:BOOL=OFF \
..
